app:
    resource: '@AppBundle/Controller/'
    type: annotation

create:
     path: /formularz
     defaults: { _controller: AppBundle:Controller:DefaultController:formularz }

update:
     path: /update/{page}
     defaults: { _controller: AppBundle:Controller:DefaultController:update, page: 1 }
     requirements:
        page: '\d+'